on: push
name: Build web version
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
        channel: dev
    - run: flutter config --enable-web
    - run: flutter pub get
    - run: flutter test
    - run: flutter build web
      with:
        artifacts: "build/web/*"
        token: ${{ secrets.TOKEN }}